### ISSUE TITLE
File truncated error message.

### ISSUE THREAD

**Issue by agoodfellow123** [florentc/xob#22] opened 2020-09-05 15:47 UTC
Hello there, using bspwm. In my bspwm config file i have the line `tail -f /tmp/xobpipe | xob &` which is supposed to open xob however whenever i start new session pipe acts wonky, sometimes show up and sometimes dont, for seeing what happens to the pipe i entered `tail -f /tmp/xobpipe | xob` in my terminal as well and looked at the output and almost whenever the value changed it gave me the error message "File truncated" only way to fix this is deleting xobpipe and recreating it with mkfifo however i really don't want to do that everytime i open bspwm, writing these commands on bspwm config file does not work so im stuck. Can anything be done about this?

**Comment by florentc** [comment] 2020-09-05 20:14
Hello,

Can you confirm there is only one xob process listening to `/tmp/xobpipe`? This could explain why sometimes a change shows up (the right xob process has consumed the value) and sometimes it does not (another process has consumed the value). I can reproduce the first issue with such a setup. In order to avoid "File truncated", maybe try appending new values with `>> /tmp/xobpipe` instead of `> /tmp/xobpipe`. I could not reproduce the "File truncated" issue.

**Comment by agoodfellow123** [comment] 2020-09-05 20:42
Hello. I did killall xob and tail processes and tried it again and it gave me the same result. However using `>>` instead of `>` seem to solve the problem with one exception, everything in my bspwm session startup runs as intended however xob wont start when i boot the pc and log into bspwm. This is really odd because when i reset my bspwm session xob starts as intended, it also works when i open bspwm first, then reset, then log out and then re login. Only when its first booted it does this issue.

**Comment by florentc** [comment] 2020-09-05 22:15
Thank you for the feedback. I will update the documentation accordingly.

Could you make sure the named pipe is created before launching xob during the startup sequence of your window manager? Maybe try sequencing the two operations with `&&` to be sure the creation of the named pipe has succeeded before launching xob.

Named pipes are kind of a generic fallback solution when you want to do things manually. You can also pipe the output of a program such as the example script in the readme, directly to xob, hence not needing to bother about managing named pipes.

**Comment by agoodfellow123** [comment] 2020-09-05 23:06
Hello again. The file "/tmp/xobpipe" never gets deleted as far as i know and trying to recreate it gives me the error `mkfifo: cannot create fifo '/tmp/xobpipe': File exists`. I did try first deleting then recreating the file at startup however probably due to bspwm's nature it couldn't run xob at all.

The example didn't worked for me because i did voice management brutally simple, for example this is all the code needed for raising the volume `pactl set-sink-volume 0 +2% && echo $(amixer get Master | awk '$0~/%/\{print $5\}' | tr -d '[]%') >> /tmp/xobpipe` and i don't know what to write as a program that can interact with pulse.

**Comment by florentc** [comment] 2020-09-08 09:07
Hello,

Can you reproduce the issue by hand, trying to emulate what happens when using bspwm? If `xobpipe` is in `/tmp/`, it probably has to be created again after each reboot. Could you also redirect the output and error output to a file when launching `tail -f /tmp/xobpipe | xob` from bspwm so we can check what goes wrong?

About using the example script (or an equivalent program): it has many advantages. You do not have to manage a named pipe and most of all, it listens to **every volume change event** in pulseaudio, not only the volume changes triggered when the user presses a dedicated key. This means that when you plug in or out headphones and the volume changes (or when another program changes the volume), the volume bar appears.

**Comment by agoodfellow123** [comment] 2020-09-08 18:11
Hello,

> Can you reproduce the issue by hand, trying to emulate what happens when using bspwm?

Everything works perfectly fine when i do them myself.

> If xobpipe is in /tmp/, it probably has to be created again after each reboot.

I did create it somewhere else and tried it, sadly it doesn't change anything.

> Could you also redirect the output and error output to a file when launching tail -f /tmp/xobpipe | xob from bspwm so we can check what goes wrong?

Sadly it seems bspwmrc does not dump anything to the system doesn't matter if it fails or not.

> About using the example script (or an equivalent program): it has many advantages. You do not have to manage a named pipe and most of all, it listens to every volume change event in pulseaudio, not only the volume changes triggered when the user presses a dedicated key. This means that when you plug in or out headphones and the volume changes (or when another program changes the volume), the volume bar appears.

I tried to use the example script, first i created with touch then i chmod +x it to be executabe and then i added `.config/bspwm/pulse-volume-watcher.py | xob` to my bspwm then installed `python-pulsectl` from aur sadly it did not work, in fact it got things more complicated, now my volume up and down buttons doesn't work and when i use them too much they lock the keyboard partially. So i probably not going to use the example script.

**Comment by florentc** [comment] 2020-09-15 22:20
Hello,

It seems this remaining issue is not related to xob itself but rather to your setup using bspwm. I am sorry I cannot be of any more help here. I will have to close the issue. I am sure there are bspwm users who use xob with a named pipe and may help you troubleshoot it. 

Meanwhile I do thank you for pointing out the "file truncated" error that can happen when following the current instructions from the documentation. This will be corrected shortly.

I am sorry to read about how the example script messes up your setup. The script should only subscribe to pulse audio events so this is weird indeed. Are your volume up and down buttons mapped in bspwm or is there some kind of volume control deamon taking care of it? Feel free to open another issue about this if you manage to identify steps to reproduce the issue.

**Closed** 2020-09-15 22:25 UTC
