### ISSUE TITLE
Hide cursor on fullscreen

### ISSUE THREAD

**Issue by lucaslira95** [florentc/xob#39] opened 2022-03-14 23:21 UTC
I'm on archlinux + i3wm...
When i'm in a fullscreen application with hidden cursor, if I do something to show xob, then my cursor blink when xob appears on screen, there is a way to make only xob bar to show on screen?

**Comment by juster-0** [comment] 2022-07-18 15:41
Hello. In which apps have you noticed the issue? And how often that occurs?

**Comment by lucaslira95** [comment] 2022-07-18 20:28
> Hello. In which apps have you noticed the issue? And how often that occurs?

I noticed it on mpv and it always occurs

**Comment by juster-0** [comment] 2022-07-19 10:40
I have the same problem with mpv, but that occurs even when xob is not running. You can test it without xob and see the same result.
I think the bug is on i3 or mpv side.

**Comment by florentc** [comment] 2022-10-29 01:07
Do you confirm this is not a bug in xob @lucaslira95 so we can close the issue?

**Comment by lucaslira95** [comment] 2022-10-29 01:32
well, i don't really know, feel free to close the issue, i'm using sway + wob now

**Closed as completed** 2022-10-29 15:44 UTC
